name: Deploy scheduler bot

# on commit push, run job
on:
  push:
    branches:
      - main

jobs:
  run:
    # worker runs on latest ubuntu
    runs-on: ubuntu-latest

    steps:
    # checkout to our repository so we have access to the source code
    - uses: actions/checkout@v2
    
    # the actual deployment to google
    - name: Deploy scheduler bot
      uses: google-github-actions/deploy-cloud-functions@v0.10.1
      with:
        credentials: ${{ secrets.GCP_SA_KEY }}
        name: odp-scheduler-scheduler-bot
        description: ODP scheduler scheduler bot
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        region: europe-west1
        # name of our function in our main.py file, defaults to the resource name suffix 
        entry_point: run_scheduler_bot
        # runtime to use for the function
        runtime: python39
        # the function execution timeout
        timeout: 60
        # the maximum number of instances for the function.
        max_instances: 1
        # optional configs, see google-cloud-actions/deploy-cloud-functions for full reference
        # list of key-value pairs to set as environment variables in the form KEY1=VALUE1,KEY2=VALUE2.
        env_vars: "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }},DISCORD_GUILD=${{ secrets.DISCORD_GUILD }},SCHEDULER_CHANNEL=${{ secrets.SCHEDULER_CHANNEL }},CAPTAINS=${{ secrets.CAPTAINS }}"